# Generated by Django 3.1.7 on 2021-03-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nascimento', models.DateField(blank=True)),
                ('contato', models.CharField(max_length=15)),
                ('mae', models.CharField(max_length=50)),
                ('pai', models.CharField(blank=True, max_length=50, null=True)),
                ('foto', models.ImageField(blank=True, upload_to='')),
                ('datecadastro', models.DateTimeField(auto_now_add=True)),
                ('dateupgrade', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
